"""Fit attribute ~ overall per position from the shipped player pool.

    python analysis/36_attribute_fit.py

Writes ui-source/src/sim/attributeFit.ts: for every position and every
attribute at least half that position's players carry, [intercept, slope,
residual sd] of attribute on overall. Generated rookies and depth players draw
their skills from it, so they have the shape real players of their overall have.
"""
import json
import statistics as st
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
pool = json.loads((ROOT / "ui-source/src/data/pool-2026.json").read_text(encoding="utf-8"))

by = {}
for p in pool:
    by.setdefault(p["position"], []).append(p)

lines = []
for pos, ps in sorted(by.items()):
    counts = {}
    for p in ps:
        for k in p.get("attributes") or {}:
            counts[k] = counts.get(k, 0) + 1
    items = []
    for k, n in sorted(counts.items()):
        if n < 0.5 * len(ps):
            continue
        xs = [p["overall"] for p in ps if k in p["attributes"]]
        ys = [p["attributes"][k] for p in ps if k in p["attributes"]]
        mx, my = st.mean(xs), st.mean(ys)
        sxx = sum((x - mx) ** 2 for x in xs)
        b = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / sxx if sxx else 0
        a = my - b * mx
        res = [y - (a + b * x) for x, y in zip(xs, ys)]
        sd = (sum(r * r for r in res) / max(1, len(res) - 2)) ** 0.5
        items.append(f"    {k}: [{a:.2f}, {b:.3f}, {sd:.2f}],")
    lines.append(f"  {pos}: {{\n" + "\n".join(items) + "\n  },")

HEADER = """/**
 * How each attribute relates to a player's overall, by position — fitted on
 * the shipped player pool (`src/data/pool-2026.json`, real players with
 * authored ratings). Each entry is `[intercept, slope, residual sd]`:
 * attribute ≈ intercept + slope × overall, give or take sd.
 *
 * Generated rookies and depth players used to get three generic attributes
 * (speed, strength, awareness) and none of the position skills the engine's
 * rating families and synergy actually read — so as a league's real players
 * retired, it filled with players the engine could not tell apart. Drawing
 * skills from this fit gives a generated player the same *shape* a real one
 * of that overall has (a 96 QB's accuracy is ~90, not 96; a lineman's pass
 * blocking tracks his overall almost exactly).
 *
 * Generated by `python analysis/36_attribute_fit.py` — edit that, not this.
 */
"""

GENERATOR = """
/**
 * Every attribute a player of this position and overall would carry, drawn
 * from the fit: the fitted value plus a normal draw of the fit's own spread.
 * `normal()` is the caller's seeded source, so a player is the same player on
 * every machine.
 */
export function fittedAttributes(
  position: string,
  overall: number,
  normal: () => number,
): Record<string, number> {
  const fit = ATTRIBUTE_FIT[position] ?? {};
  const out: Record<string, number> = {};
  for (const [key, [a, b, sd]] of Object.entries(fit)) {
    out[key] = Math.max(20, Math.min(99, Math.round(a + b * overall + normal() * sd)));
  }
  return out;
}
"""

NL = chr(10)
table = (
    "export const ATTRIBUTE_FIT: Readonly<Record<string, Readonly<Record<string, readonly [number, number, number]>>>> = {"
    + NL
    + NL.join(lines)
    + NL
    + "};"
    + NL
)
(ROOT / "ui-source/src/sim/attributeFit.ts").write_text(HEADER + table + GENERATOR, encoding="utf-8")
